version: "3"

vars:
  PROTO_DIR: proto
  GEN_DIR: gen/go
  PROTOC_INCLUDE: C:\Users\2BA0~1\AppData\Local\MICROS~1\WinGet\Packages\Google.Protobuf_Microsoft.Winget.Source_8wekyb3d8bbwe\include

tasks:

  generate-identity:
    desc: "Generate Go gRPC code for identity service"
    cmds:
      # Создаём gen/go если её нет
      - cmd: mkdir -p {{.GEN_DIR}}
        platforms: [linux, darwin]
      - cmd: cmd /c "if not exist gen\go mkdir gen\go"
        platforms: [windows]

      # Генерация
      - protoc
        --proto_path={{.PROTO_DIR}}
        --proto_path="{{.PROTOC_INCLUDE}}"
        --go_out={{.GEN_DIR}}
        --go_opt=paths=source_relative
        --go-grpc_out={{.GEN_DIR}}
        --go-grpc_opt=paths=source_relative
        {{.PROTO_DIR}}/identity/v1/common.proto
        {{.PROTO_DIR}}/identity/v1/auth.proto
        {{.PROTO_DIR}}/identity/v1/user.proto
        {{.PROTO_DIR}}/identity/v1/admin.proto

  generate:
    aliases:
      - gen
    deps:
      - generate-identity

  clean:
    desc: "Remove generated code"
    cmds:
      - cmd: rm -rf {{.GEN_DIR}}
        platforms: [linux, darwin]
      - cmd: cmd /c "if exist gen\go rmdir /s /q gen\go"
        platforms: [windows]